export type Property = {
  id: number
  title: string
  subtitle: string        // e.g. "Byt 3+kk"
  location: string
  district: string        // for filter grouping
  area: number            // m²
  rooms: string           // "2+kk" | "3+kk" | "4+kk" | "Dům" | "Komerční"
  price: number           // raw number for filtering
  priceLabel: string      // formatted display string
  type: 'Prodej' | 'Pronájem'
  status: 'available' | 'reserved' | 'sold'
  floor?: string
  year?: number
  tags: string[]
}

export const properties: Property[] = [
  {
    id: 1,
    title: 'Prostorný byt v Dejvicích',
    subtitle: 'Byt 3+kk',
    location: 'Praha 6 – Dejvice',
    district: 'Praha 6',
    area: 78,
    rooms: '3+kk',
    price: 8_900_000,
    priceLabel: '8 900 000 Kč',
    type: 'Prodej',
    status: 'available',
    floor: '3. patro',
    year: 1938,
    tags: ['Balkon', 'Cihlový dům', 'Parkování'],
  },
  {
    id: 2,
    title: 'Rodinný dům s velkou zahradou',
    subtitle: 'Rodinný dům',
    location: 'Průhonice',
    district: 'Okolí Prahy',
    area: 160,
    rooms: 'Dům',
    price: 14_500_000,
    priceLabel: '14 500 000 Kč',
    type: 'Prodej',
    status: 'reserved',
    floor: 'Přízemí',
    year: 2005,
    tags: ['Zahrada', 'Garáž', 'Sklep'],
  },
  {
    id: 3,
    title: 'Světlý byt na Vinohradech',
    subtitle: 'Byt 2+kk',
    location: 'Praha 2 – Vinohrady',
    district: 'Praha 2',
    area: 52,
    rooms: '2+kk',
    price: 24_000,
    priceLabel: '24 000 Kč / měs.',
    type: 'Pronájem',
    status: 'available',
    floor: '2. patro',
    year: 1925,
    tags: ['Cihlový dům', 'Zrekonstruovaný', 'Metro blízko'],
  },
  {
    id: 4,
    title: 'Velkorysý byt na Smíchově',
    subtitle: 'Byt 4+kk',
    location: 'Praha 5 – Smíchov',
    district: 'Praha 5',
    area: 95,
    rooms: '4+kk',
    price: 12_200_000,
    priceLabel: '12 200 000 Kč',
    type: 'Prodej',
    status: 'available',
    floor: '5. patro',
    year: 2018,
    tags: ['Novostavba', 'Terasa', 'Výtah'],
  },
  {
    id: 5,
    title: 'Moderní mezonetu Žižkov',
    subtitle: 'Byt 3+1',
    location: 'Praha 3 – Žižkov',
    district: 'Praha 3',
    area: 88,
    rooms: '3+kk',
    price: 9_750_000,
    priceLabel: '9 750 000 Kč',
    type: 'Prodej',
    status: 'available',
    floor: '4.–5. patro',
    year: 2020,
    tags: ['Mezonet', 'Střešní terasa', 'Výtah'],
  },
  {
    id: 6,
    title: 'Útulný byt k pronájmu',
    subtitle: 'Byt 1+kk',
    location: 'Praha 7 – Holešovice',
    district: 'Praha 7',
    area: 35,
    rooms: '1+kk',
    price: 18_500,
    priceLabel: '18 500 Kč / měs.',
    type: 'Pronájem',
    status: 'available',
    floor: '1. patro',
    year: 1970,
    tags: ['Zrekonstruovaný', 'MHD dostupnost'],
  },
  {
    id: 7,
    title: 'Exkluzivní penthouse Pankrác',
    subtitle: 'Byt 4+kk',
    location: 'Praha 4 – Pankrác',
    district: 'Praha 4',
    area: 135,
    rooms: '4+kk',
    price: 22_900_000,
    priceLabel: '22 900 000 Kč',
    type: 'Prodej',
    status: 'available',
    floor: '12. patro',
    year: 2022,
    tags: ['Penthouse', 'Výhled na město', 'Concierge', 'Parkování'],
  },
  {
    id: 8,
    title: 'Zahradní vila Říčany',
    subtitle: 'Rodinný dům',
    location: 'Říčany',
    district: 'Okolí Prahy',
    area: 220,
    rooms: 'Dům',
    price: 18_900_000,
    priceLabel: '18 900 000 Kč',
    type: 'Prodej',
    status: 'available',
    floor: 'Přízemí + 1. patro',
    year: 2010,
    tags: ['Bazén', 'Zahrada', 'Garáž', 'Klidná lokalita'],
  },
  {
    id: 9,
    title: 'Kancelářský prostor centrum',
    subtitle: 'Komerční prostor',
    location: 'Praha 1 – Nové Město',
    district: 'Praha 1',
    area: 64,
    rooms: 'Komerční',
    price: 38_000,
    priceLabel: '38 000 Kč / měs.',
    type: 'Pronájem',
    status: 'available',
    floor: '2. patro',
    year: 2015,
    tags: ['Centrum', 'Klimatizace', 'Recepce'],
  },
  {
    id: 10,
    title: 'Byt s výhledem na Vltavu',
    subtitle: 'Byt 2+kk',
    location: 'Praha 1 – Josefov',
    district: 'Praha 1',
    area: 61,
    rooms: '2+kk',
    price: 13_500_000,
    priceLabel: '13 500 000 Kč',
    type: 'Prodej',
    status: 'sold',
    floor: '6. patro',
    year: 1900,
    tags: ['Historická budova', 'Výhled na řeku', 'Výtah'],
  },
]

export const DISTRICTS = ['Vše', 'Praha 1', 'Praha 2', 'Praha 3', 'Praha 4', 'Praha 5', 'Praha 6', 'Praha 7', 'Okolí Prahy']
export const ROOM_TYPES = ['Vše', '1+kk', '2+kk', '3+kk', '4+kk', 'Dům', 'Komerční']
